version: '3'
services:
  glibc:
    image: indiewebconsult/glibc:alpine
    build:
      context: docker-alpine-glibc

  java:
    image: indiewebconsult/java:8-x64-alpine
    build:
      context: docker-alpine-x64-java

  androidsdk:
    image: indiewebconsult/androidsdk:alpine-java8
    build:
      context: docker-alpine-androidsdk
